from Commands.Funcs.Admin import admin
from Commands.Funcs.Birthday import birthday
from Commands.Funcs.Help import help
from Commands.Funcs.Image import image
from Commands.Funcs.Logout import logout
from Commands.Funcs.Lolgame import lolgame
from Commands.Funcs.Migrate import migrate
from Commands.Funcs.Pause import pause
from Commands.Funcs.Play import play
from Commands.Funcs.Quote import quote
from Commands.Funcs.Suggest import suggest
from Commands.Funcs.Youtube import youtube
from Commands.Funcs.Deck import deck
from Commands.Funcs.Update import update